In [1]:
#importing the libaries needed

import pandas as pd
#splittng of model
from sklearn.model_selection import train_test_split
#import the algorthims
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression

#PREPROCESSING LIBRIES

from sklearn.preprocessing import StandardScaler
#metrics for regression
from sklearn.metrics import mean_squared_error

In [2]:
df  = pd.read_csv("/content/petrol_consumption.csv")
df

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.00,3571,1976,0.525,541
1,9.00,4092,1250,0.572,524
2,9.00,3865,1586,0.580,561
3,7.50,4870,2351,0.529,414
4,8.00,4399,431,0.544,410
5,10.00,5342,1333,0.571,457
6,8.00,5319,11868,0.451,344
7,8.00,5126,2138,0.553,467
8,8.00,4447,8577,0.529,464
9,7.00,4512,8507,0.552,498
10,8.00,4391,5939,0.530,580
11,7.50,5126,14186,0.525,471
12,7.00,4817,6930,0.574,525
13,7.00,4207,6580,0.545,508
14,7.00,4332,8159,0.608,566
15,7.00,4318,10340,0.586,635
16,7.00,4206,8508,0.572,603
17,7.00,3718,4725,0.540,714
18,7.00,4716,5915,0.724,865
19,8.50,4341,6010,0.677,640
20,7.00,4593,7834,0.663,649
21,8.00,4983,602,0.602,540
22,9.00,4897,2449,0.511,464
23,9.00,4258,4686,0.517,547
24,8.50,4574,2619,0.551,460
25,9.00,3721,4746,0.544,566
26,8.00,3448,5399,0.548,577
27,7.50,3846,9061,0.579,631
28,8.00,4188,5975,0.563,574
29,9.00,3601,4650,0.493,534
30,7.00,3640,6905,0.518,571
31,7.00,3333,6594,0.513,554
32,8.00,3063,6524,0.578,577
33,7.50,3357,4121,0.547,628
34,8.00,3528,3495,0.487,487
35,6.58,3802,7834,0.629,644
36,5.00,4045,17782,0.566,640
37,7.00,3897,6385,0.586,704
38,8.50,3635,3274,0.663,648
39,7.00,4345,3905,0.672,968
40,7.00,4449,4639,0.626,587
41,7.00,3656,3985,0.563,699
42,7.00,4300,3635,0.603,632
43,7.00,3745,2611,0.508,591
44,6.00,5215,2302,0.672,782
45,9.00,4476,3942,0.571,510
46,7.00,4296,4083,0.623,610
47,7.00,5002,9794,0.593,524

In [3]:
df.columns

Index(['Petrol_tax', 'Average_income', 'Paved_Highways',
       'Population_Driver_licence(%)', 'Petrol_Consumption'],
      dtype='object')

In [4]:
X = df.drop('Petrol_Consumption', axis =1)
y = df['Petrol_Consumption']

In [5]:
X

    Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)
0         9.00            3571            1976                         0.525
1         9.00            4092            1250                         0.572
2         9.00            3865            1586                         0.580
3         7.50            4870            2351                         0.529
4         8.00            4399             431                         0.544
5        10.00            5342            1333                         0.571
6         8.00            5319           11868                         0.451
7         8.00            5126            2138                         0.553
8         8.00            4447            8577                         0.529
9         7.00            4512            8507                         0.552
10        8.00            4391            5939                         0.530
11        7.50            5126           14186                         0.525
12        7.00            4817            6930                         0.574
13        7.00            4207            6580                         0.545
14        7.00            4332            8159                         0.608
15        7.00            4318           10340                         0.586
16        7.00            4206            8508                         0.572
17        7.00            3718            4725                         0.540
18        7.00            4716            5915                         0.724
19        8.50            4341            6010                         0.677
20        7.00            4593            7834                         0.663
21        8.00            4983             602                         0.602
22        9.00            4897            2449                         0.511
23        9.00            4258            4686                         0.517
24        8.50            4574            2619                         0.551
25        9.00            3721            4746                         0.544
26        8.00            3448            5399                         0.548
27        7.50            3846            9061                         0.579
28        8.00            4188            5975                         0.563
29        9.00            3601            4650                         0.493
30        7.00            3640            6905                         0.518
31        7.00            3333            6594                         0.513
32        8.00            3063            6524                         0.578
33        7.50            3357            4121                         0.547
34        8.00            3528            3495                         0.487
35        6.58            3802            7834                         0.629
36        5.00            4045           17782                         0.566
37        7.00            3897            6385                         0.586
38        8.50            3635            3274                         0.663
39        7.00            4345            3905                         0.672
40        7.00            4449            4639                         0.626
41        7.00            3656            3985                         0.563
42        7.00            4300            3635                         0.603
43        7.00            3745            2611                         0.508
44        6.00            5215            2302                         0.672
45        9.00            4476            3942                         0.571
46        7.00            4296            4083                         0.623
47        7.00            5002            9794                         0.593

In [6]:
y

0     541
1     524
2     561
3     414
4     410
5     457
6     344
7     467
8     464
9     498
10    580
11    471
12    525
13    508
14    566
15    635
16    603
17    714
18    865
19    640
20    649
21    540
22    464
23    547
24    460
25    566
26    577
27    631
28    574
29    534
30    571
31    554
32    577
33    628
34    487
35    644
36    640
37    704
38    648
39    968
40    587
41    699
42    632
43    591
44    782
45    510
46    610
47    524
Name: Petrol_Consumption, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.3,random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((33, 4), (15, 4), (33,), (15,))

In [8]:
#standardized the dataset

ramlat = StandardScaler()
X_train = ramlat.fit_transform(X_train)
X_test = ramlat.transform(X_test)

In [9]:
#model buliding
L_model = LinearRegression() #linaer model
R_model = RandomForestRegressor() #random forest
D_model = DecisionTreeRegressor() #decesion tree model
K_model = KNeighborsRegressor()  #KNN model

In [17]:
#fitting the models
L_model.fit(X_train,y_train)
l_pred = L_model.predict(X_test)

#random forest
R_model.fit(X_train,y_train)
r_pred = R_model.predict(X_test)

#decession tree
D_model.fit(X_train,y_train)
d_pred = D_model.predict(X_test)

#knn
K_model.fit(X_train,y_train)
k_pred = K_model.predict(X_test)

In [18]:
mse = mean_squared_error(y_test, l_pred) # linear model mean squared error
print("the mean squared error for the model is:", mse)
mse_r = mean_squared_error(y_test, r_pred) # random forset  model mean squared error
print("the mean squared error for the model is:", mse_r)
mse_d = mean_squared_error(y_test, d_pred)# decision tree model mean squared error
print("the mean squared error for the model is:", mse_d)
mse_k = mean_squared_error(y_test, k_pred)# KNN model mean squared error
print("the mean squared error for the model is:", mse_k)

the mean squared error for the model is: 8076.669020354771
the mean squared error for the model is: 8852.434806666666
the mean squared error for the model is: 9234.333333333334
the mean squared error for the model is: 11212.858666666667

In [19]:

from sklearn.metrics import mean_absolute_error
mse = mean_absolute_error(y_test, l_pred) # linear model mean absolaute s error
print("the mean squared error for the model is:", mse)

the mean squared error for the model is: 63.02652446557514